### ISSUE TITLE
JMS connectors stops requiring replication factor equals to 3

### ISSUE THREAD

**Issue by ricardoatsouza** [datamountaineer/stream-reactor#286]
I'm using Stream Reactor version 0.3.0 with local Kafka from Landoop (fast-data-dev).
The goal is to move data from ActiveMQ (JMS) into a Kafka topic and, as a first trial, the idea is to make it run locally.

I have created a `docker-compose` file with the following content:

```
activemq_to_kafka:
  image: registry.hub.docker.com/datamountaineer/kafka-connect-jms:0.3.0
  environment:
    CONNECT_BOOTSTRAP_SERVERS: 192.168.99.100:9092
    CONNECT_PROGRESS_ENABLED: "true"
    CONNECTOR_CLASS: com.datamountaineer.streamreactor.connect.jms.source.JMSSourceConnector
    TASKS_MAX: 1
    CONNECT_JMS_URL: tcl://localhost:61616
    CONNECT_JMS_INITIAL_CONTEXT_FACTORY: org.apache.activemq.jndi.ActiveMQInitialContextFactory
    CONNECT_JMS_CONNECTION_FACTORY: ConnectionFactory
    CONNECT_JMS_KCQL: INSERT INTO topic SELECT * FROM jms-queue WITHTYPE QUEUE WITHCONVERTER=com.datamountaineer.streamreactor.connect.converters.source.JsonSimpleConverter
    CONNECT_JMS_QUEUES: jms_queue
    CONNECT_GROUP_ID: ActiveMQ
    CONNECT_CONFIG_STORAGE_TOPIC: test_topic
    CONNECT_OFFSET_STORAGE_TOPIC: test_topic_offsets
    CONNECT_STATUS_STORAGE_TOPIC: test_topic_status
    CONNECT_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
    CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
    CONNECT_INTERNAL_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
    CONNECT_INTERNAL_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
    CONNECT_REST_ADVERTISED_HOST_NAME: 10.41.101.123
```

When I do `docker-compose up`, after a big load of warnings, I see the following error:

```
Waiting for connect's rest API at http://10.41.101.123:
ERROR Uncaught exception in herder work thread, exiting:  (org.apache.kafka.connect.runtime.distributed.DistributedHerder)
org.apache.kafka.connect.errors.ConnectException: Error while attempting to create/find topic(s) 'test_topic_offsets'
	at org.apache.kafka.connect.util.TopicAdmin.createTopics(TopicAdmin.java:245)
	at org.apache.kafka.connect.storage.KafkaOffsetBackingStore$1.run(KafkaOffsetBackingStore.java:99)
	at org.apache.kafka.connect.util.KafkaBasedLog.start(KafkaBasedLog.java:126)
	at org.apache.kafka.connect.storage.KafkaOffsetBackingStore.start(KafkaOffsetBackingStore.java:109)
	at org.apache.kafka.connect.runtime.Worker.start(Worker.java:146)
	at org.apache.kafka.connect.runtime.AbstractHerder.startServices(AbstractHerder.java:99)
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.run(DistributedHerder.java:194)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.InvalidReplicationFactorException: replication factor: 3 larger than available brokers: 1
	at org.apache.kafka.common.internals.KafkaFutureImpl.wrapAndThrow(KafkaFutureImpl.java:45)
	at org.apache.kafka.common.internals.KafkaFutureImpl.access$000(KafkaFutureImpl.java:32)
	at org.apache.kafka.common.internals.KafkaFutureImpl$SingleWaiter.await(KafkaFutureImpl.java:89)
	at org.apache.kafka.common.internals.KafkaFutureImpl.get(KafkaFutureImpl.java:213)
	at org.apache.kafka.connect.util.TopicAdmin.createTopics(TopicAdmin.java:226)
	... 11 more
Caused by: org.apache.kafka.common.errors.InvalidReplicationFactorException: replication factor: 3 larger than available brokers: 1
```

The topics are all properly created in Kafka, and since I'm running Kafka locally (for dev reasons) it's a fact that I have only one broker. But why does it stop executing because of the replication factor issue? Shouldn't it just show a `WARN` and continue the execution?

**Comment by stheppi** [comment]
@ricardoatsouza 
Your question is not actually related to the connector at all.  
If you read the last error coming from Kafka-rest you will get the reason of why you can't have such replication: ```replication factor: 3 larger than available brokers: 1```

There is not valid reason to replicate a topic on the same broker. the broker goes down the replication won't work no? - there is no other broker instance to take over. That's the reason why Kafka is restricting duplicating data for 0 benefit.

**Comment by andrewstevenson** [comment]
@ricardoatsouza You have the environment variables wrong. The connector config should begin with CONNECTOR and the Connect Workers with CONNECT.

**Comment by andrewstevenson** [comment]
CONNECTOR_CLASS: com.datamountaineer.streamreactor.connect.jms.source.JMSSourceConnector
    TASKS_MAX: 1
    CONNECT_JMS_URL: tcl://localhost:61616
    CONNECT_JMS_INITIAL_CONTEXT_FACTORY: org.apache.activemq.jndi.ActiveMQInitialContextFactory
    CONNECT_JMS_CONNECTION_FACTORY: ConnectionFactory
    CONNECT_JMS_KCQL: INSERT INTO topic SELECT * FROM jms-queue WITHTYPE QUEUE WITHCONVERTER=com.datamountaineer.streamreactor.connect.converters.source.JsonSimpleConverter

should be CONNECTOR

**Comment by andrewstevenson** [comment]
and maybe a typo tc**l**://localhost:61616

**Comment by andrewstevenson** [comment]
also set these, which control the replication factor of connects backing topics

CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR=1
OFFSET_STORAGE_REPLICATION_FACTOR=1
STATUS_STORAGE_REPLICATION_FACTOR=1

**Comment by ricardoatsouza** [comment]
@stheppi Yes, but I created the test topic before executing the Stream Reactor, with replication  factor of 1, not 3. That's why the error message is strange to me.

@andrewstevenson Thank you for the remarks. Will let you know if it worked.

**Comment by Antwnis** [comment]
please close when solution is verified

**Comment by ricardoatsouza** [comment]
Sorry. It didn't work. I wonder if there is something wrong with Kafka connect itself, or if I'm doing any silly mistakes.

This is the current `docker-compose` file:
```
activemq_to_kafka:
  image: registry.hub.docker.com/datamountaineer/kafka-connect-jms:0.3.0
  environment:
    CONNECT_BOOTSTRAP_SERVERS: 192.168.99.100:9092
    CONNECTOR_CLASS: com.datamountaineer.streamreactor.connect.jms.source.JMSSourceConnector
    TASKS_MAX: 1
    CONNECTOR_JMS_URL: tcl://localhost:61616
    CONNECTOR_JMS_INITIAL_CONTEXT_FACTORY: org.apache.activemq.jndi.ActiveMQInitialContextFactory
    CONNECTOR_JMS_CONNECTION_FACTORY: ConnectionFactory
    CONNECTOR_JMS_KCQL: INSERT INTO topic SELECT * FROM jms-queue WITHTYPE QUEUE WITHCONVERTER=com.datamountaineer.streamreactor.connect.converters.source.JsonSimpleConverter
    CONNECTOR_JMS_QUEUES: jms_queue
    CONNECT_GROUP_ID: ActiveMQ
    CONNECT_CONFIG_STORAGE_TOPIC: ttest_topic
    CONNECT_OFFSET_STORAGE_TOPIC: ttest_topic_offsets
    CONNECT_STATUS_STORAGE_TOPIC: ttest_topic_status
    CONNECT_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
    CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
    CONNECT_INTERNAL_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
    CONNECT_INTERNAL_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
    CONNECT_REST_ADVERTISED_HOST_NAME: 10.41.101.123
    CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
    OFFSET_STORAGE_REPLICATION_FACTOR: 1
    STATUS_STORAGE_REPLICATION_FACTOR: 1
```

These are the current Kafka topics:
![image](https://user-images.githubusercontent.com/7985816/31005944-1f207c56-a4fb-11e7-89e0-589779f1a0c7.png)

It seems weird, by looking at the stack trace, that Kafka connect is trying to create a topic that already exists:

```
org.apache.kafka.connect.errors.ConnectException: Error while attempting to create/find topic(s) 'test_topic_offsets'
	at org.apache.kafka.connect.util.TopicAdmin.createTopics(TopicAdmin.java:245) <--
```

As @stheppi said, maybe it's not a problem with Stream Reactor at all, but I wonder if I am missing something.
